name: connect_chain_market
description: "ConnectChain app"

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
# State Management
  flutter_bloc: ^9.1.0       
  provider: ^6.1.4

  # DI
  get_it: ^8.0.3

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17       
  cached_network_image: ^3.4.1  
  photo_view: ^0.15.0        
  shimmer: ^3.0.0            
  smooth_page_indicator: ^1.2.1 
  dotted_border: ^2.1.0      
  fl_chart: ^0.70.2
  fluttertoast: ^8.2.12
  toastification: 3.0.1    

  # Networking
  dio: ^5.8.0+1              
  pretty_dio_logger: ^1.4.0  
  http_parser: ^4.1.2        

  # Localization
  easy_localization: ^3.0.7+1 
  intl: ^0.19.0             

  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # Firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5

  # Utilities
  flutter_screenutil: ^5.9.3 
  meta: ^1.9.1               
  mime: ^2.0.0               
  freezed_annotation: ^2.4.4 
  image_picker: ^1.1.2

  # Notification
  flutter_local_notifications: ^19.1.0


dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7

  flutter_test:
    sdk: flutter

  # Launchers
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/connect_chain_logo.png"
  min_sdk_android: 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # Font configurations
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-ExtraBold.ttf
          weight: 800

    - family: rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
