default_platform(:android)

platform :android do
  desc "Lane for Android Firebase Distribution"
  lane :distribute_chain_store_to_firebase do
    sh "flutter clean"
    sh "flutter build apk --release --obfuscate --split-debug-info=out/android --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    release = firebase_app_distribution(
            app: "1:287776857436:android:034b0bd1f5815914b63599",
            groups: "android-testers",
            release_notes: "First Version",
            firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk"
        )
  end
end